package org.testng;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CopyOnWriteArrayList;

import org.testng.util.Strings;

/**
 * This class is used for test methods to log messages that will be
 * included in the HTML reports generated by TestNG.
 * <br>
 * <br>
 * <b>Implementation details.</b>
 * <br>
 * <br>
 * The reporter keeps a combined output of strings.  In order to do this, callers
 * specify what the current method is with setCurrentTestResult().
 *
 * Created on Nov 2, 2005
 * @author cbeust
 */
public class Reporter {
  // when tests are run in parallel, each thread may be working with different
  // 'current test result'. Also, this value should be inherited if the test code
  // spawns its own thread.
  private static final ThreadLocal<ITestResult> m_currentTestResult = new InheritableThreadLocal();

  private static boolean m_escapeHtml = false;
  //This variable is responsible for persisting all output that is yet to be associated with any
  //valid TestResult objects.
  private static final ThreadLocal<List<String>> m_orphanedOutput = new InheritableThreadLocal();
  private static final Map<ITestResult, List<String>> m_testResultOutput = new HashMap();

  public static void setCurrentTestResult(ITestResult m) {
    m_currentTestResult.set(m);
  }

  public static List<String> getOutput() {
    return getOutput(getCurrentTestResult());
  }

  /**
   * Erase the content of all the output generated so far.
   */
  public static synchronized void clear() {
    getOutput().clear();
  }

  /**
   * @param escapeHtml If true, use HTML entities for special HTML characters (<, >, &, ...).
   */
  public static void setEscapeHtml(boolean escapeHtml) {
    m_escapeHtml = escapeHtml;
  }

  private static synchronized void log(String s, ITestResult m) {
    // Escape for the HTML reports
    if (m_escapeHtml) {
      s = Strings.escapeHtml(s);
    }

    if (m == null) {
      //Persist the output temporarily into a Threadlocal String list.
      if (m_orphanedOutput.get() == null) {
        m_orphanedOutput.set(new ArrayList<String>());
      }
      m_orphanedOutput.get().add(s);
      return;
    }

    // Check if there was already some orphaned output for the current thread.
    if (m_orphanedOutput.get() != null) {
      getOutput().addAll(m_orphanedOutput.get());
      // Since we have already added all of the orphaned output to the current
      // TestResult, lets clear it off
      m_orphanedOutput.remove();
    }
    getOutput().add(s);
  }

  /**
   * Log the passed string to the HTML reports
   * @param s The message to log
   */
  public static void log(String s) {
    log(s, getCurrentTestResult());
  }

  /**
   * Log the passed string to the HTML reports if the current verbosity
   * is equal or greater than the one passed in parameter. If logToStandardOut
   * is true, the string will also be printed on standard out.
   *
   * @param s The message to log
   * @param level The verbosity of this message
   * @param logToStandardOut Whether to print this string on standard
   * out too
   */
  public static void log(String s, int level, boolean logToStandardOut) {
    if (TestRunner.getVerbose() >= level) {
      log(s, getCurrentTestResult());
      if (logToStandardOut) {
        System.out.println(s);
      }
    }
  }

  /**
   * Log the passed string to the HTML reports.  If logToStandardOut
   * is true, the string will also be printed on standard out.
   *
   * @param s The message to log
   * @param logToStandardOut Whether to print this string on standard
   * out too
   */
  public static void log(String s, boolean logToStandardOut) {
    log(s, getCurrentTestResult());
    if (logToStandardOut) {
      System.out.println(s);
    }
  }
  /**
   * Log the passed string to the HTML reports if the current verbosity
   * is equal or greater than the one passed in parameter
   *
   * @param s The message to log
   * @param level The verbosity of this message
   */
  public static void log(String s, int level) {
    if (TestRunner.getVerbose() >= level) {
      log(s, getCurrentTestResult());
    }
  }

  /**
   * @return the current test result.
   */
  public static ITestResult getCurrentTestResult() {
    return m_currentTestResult.get();
  }

  public static synchronized List<String> getOutput(ITestResult tr) {
    List<String> result = m_testResultOutput.get(tr);

    if (result == null) {
      result = new CopyOnWriteArrayList();
      m_testResultOutput.put(tr, result);
    }

    if (tr == null) {
      return result; 
    }

    return result;
  }
}
