package org.testng;

import static java.util.Objects.requireNonNull;
import static org.assertj.core.api.Assertions.assertThat;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLClassLoader;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.jar.JarEntry;
import java.util.jar.JarOutputStream;
import org.jspecify.annotations.Nullable;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import org.testng.jarfileutils.org.testng.SampleTest1;
import org.testng.testhelper.JarCreator;
import org.testng.xml.IPostProcessor;
import org.testng.xml.XmlClass;
import org.testng.xml.XmlSuite;
import org.testng.xml.XmlTest;

public class JarFileUtilsTest {

  private static @Nullable File jar;

  @BeforeClass
  public void generateTestJar() throws IOException {
    jar = JarCreator.generateJar();
  }

  private static File jar() {
    return requireNonNull(jar, "the test jar is generated by @BeforeClass, before any test runs");
  }

  @Test
  public void testWithValidTestNames() throws MalformedURLException {
    JarFileUtils utils = newJarFileUtils(Collections.singletonList("testng-tests-child1"));
    runTest(
        utils,
        1,
        new String[] {"testng-tests-child1"},
        new String[] {"org.testng.jarfileutils.org.testng.SampleTest1"});
  }

  @Test
  public void testWithNoTestNames() throws MalformedURLException {
    JarFileUtils utils = newJarFileUtils(null);
    runTest(
        utils,
        3,
        new String[] {"testng-tests-child1", "testng-tests-child2", "testng-tests-child3"},
        new String[] {
          "org.testng.jarfileutils.org.testng.SampleTest1",
          "org.testng.jarfileutils.org.testng.SampleTest2",
          "org.testng.jarfileutils.org.testng.SampleTest3"
        });
  }

  @Test(
      expectedExceptions = TestNGException.class,
      expectedExceptionsMessageRegExp =
          "\nThe test\\(s\\) <\\[testng-tests-child11\\]> cannot be found in suite.")
  public void testWithInvalidTestNames() throws MalformedURLException {
    JarFileUtils utils = newJarFileUtils(Collections.singletonList("testng-tests-child11"));
    runTest(
        utils,
        1,
        new String[] {"testng-tests-child1"},
        new String[] {"org.testng.jarfileutils.org.testng.SampleTest1"});
  }

  @Test(
      description =
          "GITHUB-2897, Have TestNGException thrown when ignoreMissedTestNames enabled and ALL given test names are invalid.",
      expectedExceptions = TestNGException.class,
      expectedExceptionsMessageRegExp =
          "\nThe test\\(s\\) <\\[testng-tests-child11\\]> cannot be found in suite.")
  public void testWithAllInvalidTestNamesNoExceptionIfIgnoreMissedTestNamesEnabled()
      throws MalformedURLException {
    boolean ignoreMissedTestNames = true;
    JarFileUtils utils =
        newJarFileUtils(Collections.singletonList("testng-tests-child11"), ignoreMissedTestNames);
    runTest(utils, 1, null, null, "Jar suite");
  }

  @Test(
      description =
          "GITHUB-2897, No TestNGException thrown when ignoreMissedTestNames enabled and partial given test names are invalid and partial valid test names are expected to run.")
  public void testWithPartialInvalidTestNamesNoExceptionIfIgnoreMissedTestNamesEnabled()
      throws MalformedURLException {
    String[] expectedTestNames =
        new String[] {"testng-tests-child2", "testng-tests-child4", "testng-tests-child5"};
    String[] expectedClassNames =
        new String[] {
          "org.testng.jarfileutils.org.testng.SampleTest2",
          "org.testng.jarfileutils.org.testng.SampleTest4",
          "org.testng.jarfileutils.org.testng.SampleTest5"
        };
    List<String> testNames =
        Arrays.asList(
            "testng-tests-child2", "testng-tests-child4", "testng-tests-child5", "invalid");
    boolean ignoreMissedTestNames = true;
    JarFileUtils utils = newJarFileUtils(testNames, ignoreMissedTestNames);
    // 3 tests from 3 suites, the first suite has one test is given
    runTest(utils, 1, 3, expectedTestNames, expectedClassNames, "testng-tests-suite");
  }

  @Test(description = "GITHUB-2333")
  public void moduleInfoClassEntriesAreNotTreatedAsTestClasses() throws IOException {
    File jarWithModuleInfo = jarWithModuleInfoDescriptors();
    JarFileUtils utils = new JarFileUtils(new FakeProcessor(), "missing-suite.xml", null);
    List<XmlSuite> suites = utils.extractSuitesFrom(jarWithModuleInfo);
    List<String> classNames = new ArrayList<>();
    extractClassNames(suites, new ArrayList<>(), classNames);
    assertThat(classNames).containsExactly("org.testng.jarfileutils.org.testng.SampleTest1");
  }

  @Test
  public void testWithInvalidXmlFile() throws MalformedURLException {
    JarFileUtils utils =
        newJarFileUtils(
            "invalid-testng-tests.xml", Collections.singletonList("testng-tests-child11"));
    runTest(
        utils,
        1,
        null,
        new String[] {
          "org.testng.jarfileutils.org.testng.SampleTest1",
          "org.testng.jarfileutils.org.testng.SampleTest2",
          "org.testng.jarfileutils.org.testng.SampleTest3"
        },
        "Jar suite");
  }

  /**
   * Test to ensure that exception is not thrown. Ensure that GITHUB-2709 can not happen again.
   *
   * @throws MalformedURLException
   */
  @Test
  public void ensureThatExceptionAreNotThrown() throws MalformedURLException {
    TestNG testNg = new TestNG(false);
    List<String> testNames =
        Arrays.asList("testng-tests-child2", "testng-tests-child4", "testng-tests-child5");
    testNg.setTestNames(testNames);
    testNg.setXmlPathInJar("jarfileutils/testng-tests.xml");
    testNg.setTestJar(jar().getAbsolutePath());
    testNg.initializeSuitesAndJarFile();
    // "testng-tests-child2", "testng-tests-child4", "testng-tests-child5" are from 3 different test
    // suites
    assertThat(testNg.m_suites.size()).isEqualTo(3);
  }

  /**
   * Test to ensure that exception is thrown for invalid test name.
   *
   * @throws MalformedURLException
   */
  @Test(
      expectedExceptions = TestNGException.class,
      expectedExceptionsMessageRegExp = "\nThe test\\(s\\) <\\[dummy\\]> cannot be found in suite.")
  public void ensureThatExceptionAreThrown() throws MalformedURLException {
    TestNG testNg = new TestNG(false);
    List<String> testNames =
        Arrays.asList("testng-tests-child2", "testng-tests-child4", "testng-tests-child5", "dummy");
    testNg.setTestNames(testNames);
    testNg.setXmlPathInJar("jarfileutils/testng-tests.xml");
    testNg.setTestJar(jar().getAbsolutePath());
    testNg.initializeSuitesAndJarFile();
    assertThat(testNg.m_suites.size()).isEqualTo(1);
  }

  @Test
  public void testWithValidTestNamesFromMultiChildSuites() throws MalformedURLException {
    JarFileUtils utils =
        newJarFileUtils(
            Arrays.asList("testng-tests-child2", "testng-tests-child4", "testng-tests-child5"));
    String[] expectedTestNames =
        new String[] {"testng-tests-child2", "testng-tests-child4", "testng-tests-child5"};
    String[] expectedClassNames =
        new String[] {
          "org.testng.jarfileutils.org.testng.SampleTest2",
          "org.testng.jarfileutils.org.testng.SampleTest4",
          "org.testng.jarfileutils.org.testng.SampleTest5"
        };
    List<XmlSuite> suites = utils.extractSuitesFrom(jar());
    assertThat(suites).hasSize(3);
    XmlSuite suite = suites.get(0);
    assertThat(suite.getName()).isEqualTo("testng-tests-suite");
    List<String> testNames = new ArrayList<>();
    List<String> classNames = new ArrayList<>();
    extractClassNames(suites, testNames, classNames);

    assertThat(testNames).containsExactly(expectedTestNames);
    assertThat(classNames).contains(expectedClassNames);
  }

  private static void extractClassNames(
      List<XmlSuite> xmlSuites, List<String> testNames, List<String> classNames) {
    for (XmlSuite xmlSuite : xmlSuites) {
      for (XmlTest xmlTest : xmlSuite.getTests()) {
        testNames.add(xmlTest.getName());
        for (XmlClass xmlClass : xmlTest.getXmlClasses()) {
          classNames.add(xmlClass.getName());
        }
      }
    }
  }

  private static void runTest(
      JarFileUtils utils,
      int numberOfTests,
      String @Nullable [] expectedTestNames,
      String @Nullable [] expectedClassNames) {
    runTest(utils, numberOfTests, expectedTestNames, expectedClassNames, "testng-tests-suite");
  }

  private static void runTest(
      JarFileUtils utils,
      int numberOfTests,
      String @Nullable [] expectedTestNames,
      String @Nullable [] expectedClassNames,
      String expectedSuiteName) {
    runTest(utils, numberOfTests, 1, expectedTestNames, expectedClassNames, expectedSuiteName);
  }

  /** A null expectation means "do not check this list", which is why both are nullable. */
  private static void runTest(
      JarFileUtils utils,
      int numberOfTests,
      int expectedSuiteTotal,
      String @Nullable [] expectedTestNames,
      String @Nullable [] expectedClassNames,
      String expectedSuiteName) {
    List<XmlSuite> suites = utils.extractSuitesFrom(jar());
    assertThat(suites).hasSize(expectedSuiteTotal);
    XmlSuite suite = suites.get(0);
    assertThat(suite.getName()).isEqualTo(expectedSuiteName);
    assertThat(suite.getTests()).hasSize(numberOfTests);
    List<String> testNames = new ArrayList<>();
    List<String> classNames = new ArrayList<>();
    extractClassNames(suites, testNames, classNames);
    if (expectedTestNames != null) {
      assertThat(testNames).containsExactly(expectedTestNames);
    }
    if (expectedClassNames != null) {
      assertThat(classNames).contains(expectedClassNames);
    }
  }

  private static File jarWithModuleInfoDescriptors() throws IOException {
    File jarFile = File.createTempFile("testng-module-info", ".jar");
    jarFile.deleteOnExit();
    String classEntry = SampleTest1.class.getName().replace('.', '/') + ".class";
    try (JarOutputStream jos = new JarOutputStream(Files.newOutputStream(jarFile.toPath()));
        InputStream classBytes =
            SampleTest1.class.getClassLoader().getResourceAsStream(classEntry)) {
      jos.putNextEntry(new JarEntry(classEntry));
      requireNonNull(classBytes, classEntry).transferTo(jos);
      jos.closeEntry();
      jos.putNextEntry(new JarEntry("module-info.class"));
      jos.write(new byte[] {0});
      jos.closeEntry();
      jos.putNextEntry(new JarEntry("META-INF/versions/9/module-info.class"));
      jos.write(new byte[] {0});
      jos.closeEntry();
    }
    return jarFile;
  }

  public static class FakeProcessor implements IPostProcessor {

    @Override
    public Collection<XmlSuite> process(Collection<XmlSuite> suites) {
      return suites;
    }
  }

  private static JarFileUtils newJarFileUtils(@Nullable List<String> testNames)
      throws MalformedURLException {
    return newJarFileUtils(testNames, false);
  }

  private static JarFileUtils newJarFileUtils(
      @Nullable List<String> testNames, boolean ignoreMissedTestNames)
      throws MalformedURLException {
    return newJarFileUtils("jarfileutils/testng-tests.xml", testNames, ignoreMissedTestNames);
  }

  private static JarFileUtils newJarFileUtils(String suiteXmlName, @Nullable List<String> testNames)
      throws MalformedURLException {
    return newJarFileUtils(suiteXmlName, testNames, false);
  }

  private static JarFileUtils newJarFileUtils(
      String suiteXmlName, @Nullable List<String> testNames, boolean ignoreMissedTestNames)
      throws MalformedURLException {
    URL url = jar().toURI().toURL();
    URLClassLoader classLoader =
        new URLClassLoader(new URL[] {url}, ClassLoader.getSystemClassLoader());
    Thread.currentThread().setContextClassLoader(classLoader);
    return new JarFileUtils(new FakeProcessor(), suiteXmlName, testNames, ignoreMissedTestNames);
  }
}
