name: Label Commenter

on:
  issues:
    types: [labeled]

permissions:
  contents: read
  issues: write

jobs:
  comment:
    if: github.repository_owner == 'testng-team'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Label Commenter
        uses: peaceiris/actions-label-commenter@f0dbbef043eb1b150b566db36b0bdc8b7f505579 # v1
