name: Label Commenter

on:
  issues:
    types: [labeled]

permissions:
  contents: read
  issues: write

jobs:
  comment:
    if: github.repository_owner == 'testng-team'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: Label Commenter
        uses: peaceiris/actions-label-commenter@f0dbbef043eb1b150b566db36b0bdc8b7f505579 # v1
